version: 2
jobs:
  build:
#    machine: true
    docker:
      - image: perl:latest
    steps:
      - checkout
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            # Test th help
            . test/environment.sh
            perl check_glusterfs.pl --help || [ "$?" == "3" ]
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#          paths:
#            - "venv"
      - store_artifacts:
          path: test-reports/
          destination: test-reports

