version: 2
jobs:
  build:
    machine: true
#    docker:
#      - image: circleci/python:3.6.1
#      - image: circleci/postgres:9.6.2
#        environment:
#          POSTGRES_USER: root
#          POSTGRES_DB: circle_test
    steps:
      - checkout
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . test/environment.sh
            perl check_glusterfs.pl --help
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#          paths:
#            - "venv"
      - store_artifacts:
          path: test-reports/
          destination: test-reports

