version: 2
jobs:
  build:
#    machine: true
    docker:
      - image: perl:latest
    steps:
      # Get src
      - checkout
      # Install requirements
      - restore_cache:
          key: requirements-{{ .Branch }}-{{ checksum "test/requirements.txt" }}
      - run:
          command: "cat test/requirements.txt | xargs cpan -i"
      - save_cache:
          key: requirements-{{ .Branch }}-{{ checksum "test/requirements.txt" }}
          paths:
            - ".cpan"
      # Run tests
      - run:
          command: "perl test/runUseCaseTests.pl --level 999 --output XML"
      # Store test reports
      - store_test_results:
          path: test-reports/

